{ Nama          : Mohammad Ihsan Siddiq }
{ Npm           : 20.14.1.0005 }
{ Nama Program  :Biodata }

program biodata_singkat;
uses crt;
var
Nama,Npm,Alamat,TTL,NoHP,Motto :string;
begin
writeln('Nam: Mohammad ihsan siddiq');readln;
writeln('Npm: 20.14.1.0005');readln;
writeln('Alamat: Kp cigelang Desa gunungbatu Kecamatan ciracap Kabupaten sukabumi');readln;
writeln('TTL: Sukabumi,03 November 2001');readln;
writeln('NoHP: 085794536354');readln;
writeln('Motto: AKU TANPA ALLAH BUKAN APA APA');readln;

readln;
end.